python track.py -t KCF -d Professor_car1 >> kcf_results.txt
python track.py -t KCF -d Professor_car2 >> kcf_results.txt
python track.py -t KCF -d Babenko_OccludedFace2 >> kcf_results.txt
python track.py -t KCF -d Babenko_surfer >> kcf_results.txt
python track.py -t KCF -d Cehovin_dinosaur >> kcf_results.txt
python track.py -t KCF -d Cehovin_gymnastics >> kcf_results.txt
python track.py -t KCF -d Cehovin_hand >> kcf_results.txt
python track.py -t KCF -d Cehovin_hand2 >> kcf_results.txt
python track.py -t KCF -d Cehovin_torus >> kcf_results.txt
python track.py -t KCF -d Ellis_ijcv2011_head_motion >> kcf_results.txt
python track.py -t KCF -d Ellis_ijcv2011_track_running >> kcf_results.txt
python track.py -t KCF -d Ellis_ijcv2011_shaking_camera >> kcf_results.txt
python track.py -t KCF -d Godec_cliff-dive1 >> kcf_results.txt
python track.py -t KCF -d Godec_cliff-dive2 >> kcf_results.txt
python track.py -t KCF -d Godec_motocross1 >> kcf_results.txt
python track.py -t KCF -d Godec_motocross2 >> kcf_results.txt
python track.py -t KCF -d Godec_mountain-bike >> kcf_results.txt
python track.py -t KCF -d Godec_skiing >> kcf_results.txt
python track.py -t KCF -d Godec_volleyball >> kcf_results.txt
python track.py -t KCF -d Kalal_car >> kcf_results.txt
python track.py -t KCF -d Kalal_CarChase >> kcf_results.txt
python track.py -t KCF -d Kalal_david >> kcf_results.txt
python track.py -t KCF -d Kalal_jumping >> kcf_results.txt
python track.py -t KCF -d Kalal_Motocross >> kcf_results.txt
python track.py -t KCF -d Kalal_Panda >> kcf_results.txt
python track.py -t KCF -d Kalal_pedestrian3 >> kcf_results.txt
python track.py -t KCF -d Kalal_pedestrian4 >> kcf_results.txt
python track.py -t KCF -d Kalal_pedestrian5 >> kcf_results.txt
python track.py -t KCF -d Kwon_diving >> kcf_results.txt
python track.py -t KCF -d Kwon_gym  >> kcf_results.txt
python track.py -t KCF -d Kwon_jump >> kcf_results.txt
python track.py -t KCF -d Kwon_trans >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_animal >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_basketball >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_football >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_shaking >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_singer1 >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_singer2 >> kcf_results.txt
python track.py -t KCF -d Kwon_VTD_skating2 >> kcf_results.txt
python track.py -t KCF -d Other_Asada >> kcf_results.txt
python track.py -t KCF -d Other_drunk2 >> kcf_results.txt
python track.py -t KCF -d Other_dudek-face >> kcf_results.txt
python track.py -t KCF -d Other_faceocc1 >> kcf_results.txt
python track.py -t KCF -d Other_figure_skating >> kcf_results.txt
python track.py -t KCF -d Other_woman >> kcf_results.txt
python track.py -t KCF -d PROST_board >> kcf_results.txt
python track.py -t KCF -d PROST_box >> kcf_results.txt
python track.py -t KCF -d PROST_lemming >> kcf_results.txt
python track.py -t KCF -d PROST_liquor >> kcf_results.txt
python track.py -t KCF -d Ross_car11 >> kcf_results.txt
python track.py -t KCF -d Ross_dog1 >> kcf_results.txt
python track.py -t KCF -d Ross_Sylvestr >> kcf_results.txt
python track.py -t KCF -d Ross_trellis >> kcf_results.txt
python track.py -t KCF -d Thang_coke >> kcf_results.txt
python track.py -t KCF -d Thang_person >> kcf_results.txt
python track.py -t KCF -d Thang_tiger1 >> kcf_results.txt
python track.py -t KCF -d Thang_tiger2 >> kcf_results.txt
python track.py -t KCF -d Wang_bird_1 >> kcf_results.txt
python track.py -t KCF -d Wang_bird_2 >> kcf_results.txt
python track.py -t KCF -d Wang_bolt >> kcf_results.txt
python track.py -t KCF -d Wang_girl_mov >> kcf_results.txt