python track.py -d Professor_car1 >> results/boosting_results.txt
python track.py -d Professor_car2 >> results/boosting_results.txt
python track.py -d Babenko_OccludedFace2 >> results/boosting_results.txt
python track.py -d Babenko_surfer >> results/boosting_results.txt
python track.py -d Cehovin_dinosaur >> results/boosting_results.txt
python track.py -d Cehovin_gymnastics >> results/boosting_results.txt
python track.py -d Cehovin_hand >> results/boosting_results.txt
python track.py -d Cehovin_hand2 >> results/boosting_results.txt
python track.py -d Cehovin_torus >> results/boosting_results.txt
python track.py -d Ellis_ijcv2011_head_motion >> results/boosting_results.txt
python track.py -d Ellis_ijcv2011_track_running >> results/boosting_results.txt
python track.py -d Ellis_ijcv2011_shaking_camera >> results/boosting_results.txt
python track.py -d Godec_cliff-dive1 >> results/boosting_results.txt
python track.py -d Godec_cliff-dive2 >> results/boosting_results.txt
python track.py -d Godec_motocross1 >> results/boosting_results.txt
python track.py -d Godec_motocross2 >> results/boosting_results.txt
python track.py -d Godec_mountain-bike >> results/boosting_results.txt
python track.py -d Godec_skiing >> results/boosting_results.txt
python track.py -d Godec_volleyball >> results/boosting_results.txt
python track.py -d Kalal_car >> results/boosting_results.txt
python track.py -d Kalal_CarChase >> results/boosting_results.txt
python track.py -d Kalal_david >> results/boosting_results.txt
python track.py -d Kalal_jumping >> results/boosting_results.txt
python track.py -d Kalal_Motocross >> results/boosting_results.txt
python track.py -d Kalal_Panda >> results/boosting_results.txt
python track.py -d Kalal_pedestrian3 >> results/boosting_results.txt
python track.py -d Kalal_pedestrian4 >> results/boosting_results.txt
python track.py -d Kalal_pedestrian5 >> results/boosting_results.txt
python track.py -d Kwon_diving >> results/boosting_results.txt
python track.py -d Kwon_gym  >> results/boosting_results.txt
python track.py -d Kwon_jump >> results/boosting_results.txt
python track.py -d Kwon_trans >> results/boosting_results.txt
python track.py -d Kwon_VTD_animal >> results/boosting_results.txt
python track.py -d Kwon_VTD_basketball >> results/boosting_results.txt
python track.py -d Kwon_VTD_football >> results/boosting_results.txt
python track.py -d Kwon_VTD_shaking >> results/boosting_results.txt
python track.py -d Kwon_VTD_singer1 >> results/boosting_results.txt
python track.py -d Kwon_VTD_singer2 >> results/boosting_results.txt
python track.py -d Kwon_VTD_skating2 >> results/boosting_results.txt
python track.py -d Other_Asada >> results/boosting_results.txt
python track.py -d Other_drunk2 >> results/boosting_results.txt
python track.py -d Other_dudek-face >> results/boosting_results.txt
python track.py -d Other_faceocc1 >> results/boosting_results.txt
python track.py -d Other_figure_skating >> results/boosting_results.txt
python track.py -d Other_woman >> results/boosting_results.txt
python track.py -d PROST_board >> results/boosting_results.txt
python track.py -d PROST_box >> results/boosting_results.txt
python track.py -d PROST_lemming >> results/boosting_results.txt
python track.py -d PROST_liquor >> results/boosting_results.txt
python track.py -d Ross_car11 >> results/boosting_results.txt
python track.py -d Ross_dog1 >> results/boosting_results.txt
python track.py -d Ross_Sylvestr >> results/boosting_results.txt
python track.py -d Ross_trellis >> results/boosting_results.txt
python track.py -d Thang_coke >> results/boosting_results.txt
python track.py -d Thang_person >> results/boosting_results.txt
python track.py -d Thang_tiger1 >> results/boosting_results.txt
python track.py -d Thang_tiger2 >> results/boosting_results.txt
python track.py -d Wang_bird_1 >> results/boosting_results.txt
python track.py -d Wang_bird_2 >> results/boosting_results.txt
python track.py -d Wang_bolt >> results/boosting_results.txt
python track.py -d Wang_girl_mov >> results/boosting_results.txt