python track.py -t KCF -d Professor_car1 >> results/kcf_results.txt
python track.py -t KCF -d Professor_car2 >> results/kcf_results.txt
python track.py -t KCF -d Babenko_OccludedFace2 >> results/kcf_results.txt
python track.py -t KCF -d Babenko_surfer >> results/kcf_results.txt
python track.py -t KCF -d Cehovin_dinosaur >> results/kcf_results.txt
python track.py -t KCF -d Cehovin_gymnastics >> results/kcf_results.txt
python track.py -t KCF -d Cehovin_hand >> results/kcf_results.txt
python track.py -t KCF -d Cehovin_hand2 >> results/kcf_results.txt
python track.py -t KCF -d Cehovin_torus >> results/kcf_results.txt
python track.py -t KCF -d Ellis_ijcv2011_head_motion >> results/kcf_results.txt
python track.py -t KCF -d Ellis_ijcv2011_track_running >> results/kcf_results.txt
python track.py -t KCF -d Ellis_ijcv2011_shaking_camera >> results/kcf_results.txt
python track.py -t KCF -d Godec_cliff-dive1 >> results/kcf_results.txt
python track.py -t KCF -d Godec_cliff-dive2 >> results/kcf_results.txt
python track.py -t KCF -d Godec_motocross1 >> results/kcf_results.txt
python track.py -t KCF -d Godec_motocross2 >> results/kcf_results.txt
python track.py -t KCF -d Godec_mountain-bike >> results/kcf_results.txt
python track.py -t KCF -d Godec_skiing >> results/kcf_results.txt
python track.py -t KCF -d Godec_volleyball >> results/kcf_results.txt
python track.py -t KCF -d Kalal_car >> results/kcf_results.txt
python track.py -t KCF -d Kalal_CarChase >> results/kcf_results.txt
python track.py -t KCF -d Kalal_david >> results/kcf_results.txt
python track.py -t KCF -d Kalal_jumping >> results/kcf_results.txt
python track.py -t KCF -d Kalal_Motocross >> results/kcf_results.txt
python track.py -t KCF -d Kalal_Panda >> results/kcf_results.txt
python track.py -t KCF -d Kalal_pedestrian3 >> results/kcf_results.txt
python track.py -t KCF -d Kalal_pedestrian4 >> results/kcf_results.txt
python track.py -t KCF -d Kalal_pedestrian5 >> results/kcf_results.txt
python track.py -t KCF -d Kwon_diving >> results/kcf_results.txt
python track.py -t KCF -d Kwon_gym  >> results/kcf_results.txt
python track.py -t KCF -d Kwon_jump >> results/kcf_results.txt
python track.py -t KCF -d Kwon_trans >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_animal >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_basketball >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_football >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_shaking >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_singer1 >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_singer2 >> results/kcf_results.txt
python track.py -t KCF -d Kwon_VTD_skating2 >> results/kcf_results.txt
python track.py -t KCF -d Other_Asada >> results/kcf_results.txt
python track.py -t KCF -d Other_drunk2 >> results/kcf_results.txt
python track.py -t KCF -d Other_dudek-face >> results/kcf_results.txt
python track.py -t KCF -d Other_faceocc1 >> results/kcf_results.txt
python track.py -t KCF -d Other_figure_skating >> results/kcf_results.txt
python track.py -t KCF -d Other_woman >> results/kcf_results.txt
python track.py -t KCF -d PROST_board >> results/kcf_results.txt
python track.py -t KCF -d PROST_box >> results/kcf_results.txt
python track.py -t KCF -d PROST_lemming >> results/kcf_results.txt
python track.py -t KCF -d PROST_liquor >> results/kcf_results.txt
python track.py -t KCF -d Ross_car11 >> results/kcf_results.txt
python track.py -t KCF -d Ross_dog1 >> results/kcf_results.txt
python track.py -t KCF -d Ross_Sylvestr >> results/kcf_results.txt
python track.py -t KCF -d Ross_trellis >> results/kcf_results.txt
python track.py -t KCF -d Thang_coke >> results/kcf_results.txt
python track.py -t KCF -d Thang_person >> results/kcf_results.txt
python track.py -t KCF -d Thang_tiger1 >> results/kcf_results.txt
python track.py -t KCF -d Thang_tiger2 >> results/kcf_results.txt
python track.py -t KCF -d Wang_bird_1 >> results/kcf_results.txt
python track.py -t KCF -d Wang_bird_2 >> results/kcf_results.txt
python track.py -t KCF -d Wang_bolt >> results/kcf_results.txt
python track.py -t KCF -d Wang_girl_mov >> results/kcf_results.txt