python track.py -t MEDIANFLOW -d Professor_car1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Professor_car2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Babenko_OccludedFace2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Babenko_surfer >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Cehovin_dinosaur >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Cehovin_gymnastics >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Cehovin_hand >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Cehovin_hand2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Cehovin_torus >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ellis_ijcv2011_head_motion >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ellis_ijcv2011_track_running >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ellis_ijcv2011_shaking_camera >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_cliff-dive1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_cliff-dive2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_motocross1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_motocross2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_mountain-bike >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_skiing >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Godec_volleyball >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_car >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_CarChase >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_david >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_jumping >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_Motocross >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_Panda >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_pedestrian3 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_pedestrian4 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kalal_pedestrian5 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_diving >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_gym  >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_jump >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_trans >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_animal >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_basketball >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_football >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_shaking >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_singer1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_singer2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Kwon_VTD_skating2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Other_Asada >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Other_drunk2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Other_dudek-face >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Other_faceocc1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Other_figure_skating >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Other_woman >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d PROST_board >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d PROST_box >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d PROST_lemming >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d PROST_liquor >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ross_car11 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ross_dog1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ross_Sylvestr >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Ross_trellis >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Thang_coke >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Thang_person >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Thang_tiger1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Thang_tiger2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Wang_bird_1 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Wang_bird_2 >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Wang_bolt >> results/medianflow_results.txt
python track.py -t MEDIANFLOW -d Wang_girl_mov >> results/medianflow_results.txt