python track.py -t MIL -d Professor_car1 >> results/mil_results.txt
python track.py -t MIL -d Professor_car2 >> results/mil_results.txt
python track.py -t MIL -d Babenko_OccludedFace2 >> results/mil_results.txt
python track.py -t MIL -d Babenko_surfer >> results/mil_results.txt
python track.py -t MIL -d Cehovin_dinosaur >> results/mil_results.txt
python track.py -t MIL -d Cehovin_gymnastics >> results/mil_results.txt
python track.py -t MIL -d Cehovin_hand >> results/mil_results.txt
python track.py -t MIL -d Cehovin_hand2 >> results/mil_results.txt
python track.py -t MIL -d Cehovin_torus >> results/mil_results.txt
python track.py -t MIL -d Ellis_ijcv2011_head_motion >> results/mil_results.txt
python track.py -t MIL -d Ellis_ijcv2011_track_running >> results/mil_results.txt
python track.py -t MIL -d Ellis_ijcv2011_shaking_camera >> results/mil_results.txt
python track.py -t MIL -d Godec_cliff-dive1 >> results/mil_results.txt
python track.py -t MIL -d Godec_cliff-dive2 >> results/mil_results.txt
python track.py -t MIL -d Godec_motocross1 >> results/mil_results.txt
python track.py -t MIL -d Godec_motocross2 >> results/mil_results.txt
python track.py -t MIL -d Godec_mountain-bike >> results/mil_results.txt
python track.py -t MIL -d Godec_skiing >> results/mil_results.txt
python track.py -t MIL -d Godec_volleyball >> results/mil_results.txt
python track.py -t MIL -d Kalal_car >> results/mil_results.txt
python track.py -t MIL -d Kalal_CarChase >> results/mil_results.txt
python track.py -t MIL -d Kalal_david >> results/mil_results.txt
python track.py -t MIL -d Kalal_jumping >> results/mil_results.txt
python track.py -t MIL -d Kalal_Motocross >> results/mil_results.txt
python track.py -t MIL -d Kalal_Panda >> results/mil_results.txt
python track.py -t MIL -d Kalal_pedestrian3 >> results/mil_results.txt
python track.py -t MIL -d Kalal_pedestrian4 >> results/mil_results.txt
python track.py -t MIL -d Kalal_pedestrian5 >> results/mil_results.txt
python track.py -t MIL -d Kwon_diving >> results/mil_results.txt
python track.py -t MIL -d Kwon_gym  >> results/mil_results.txt
python track.py -t MIL -d Kwon_jump >> results/mil_results.txt
python track.py -t MIL -d Kwon_trans >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_animal >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_basketball >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_football >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_shaking >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_singer1 >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_singer2 >> results/mil_results.txt
python track.py -t MIL -d Kwon_VTD_skating2 >> results/mil_results.txt
python track.py -t MIL -d Other_Asada >> results/mil_results.txt
python track.py -t MIL -d Other_drunk2 >> results/mil_results.txt
python track.py -t MIL -d Other_dudek-face >> results/mil_results.txt
python track.py -t MIL -d Other_faceocc1 >> results/mil_results.txt
python track.py -t MIL -d Other_figure_skating >> results/mil_results.txt
python track.py -t MIL -d Other_woman >> results/mil_results.txt
python track.py -t MIL -d PROST_board >> results/mil_results.txt
python track.py -t MIL -d PROST_box >> results/mil_results.txt
python track.py -t MIL -d PROST_lemming >> results/mil_results.txt
python track.py -t MIL -d PROST_liquor >> results/mil_results.txt
python track.py -t MIL -d Ross_car11 >> results/mil_results.txt
python track.py -t MIL -d Ross_dog1 >> results/mil_results.txt
python track.py -t MIL -d Ross_Sylvestr >> results/mil_results.txt
python track.py -t MIL -d Ross_trellis >> results/mil_results.txt
python track.py -t MIL -d Thang_coke >> results/mil_results.txt
python track.py -t MIL -d Thang_person >> results/mil_results.txt
python track.py -t MIL -d Thang_tiger1 >> results/mil_results.txt
python track.py -t MIL -d Thang_tiger2 >> results/mil_results.txt
python track.py -t MIL -d Wang_bird_1 >> results/mil_results.txt
python track.py -t MIL -d Wang_bird_2 >> results/mil_results.txt
python track.py -t MIL -d Wang_bolt >> results/mil_results.txt
python track.py -t MIL -d Wang_girl_mov >> results/mil_results.txt