python track_alt.py -p -d Professor_car1 >> results/particle_results.txt
python track_alt.py -p -d Professor_car2 >> results/particle_results.txt
python track_alt.py -p -d Babenko_OccludedFace2 >> results/particle_results.txt
python track_alt.py -p -d Babenko_surfer >> results/particle_results.txt
python track_alt.py -p -d Cehovin_dinosaur >> results/particle_results.txt
python track_alt.py -p -d Cehovin_gymnastics >> results/particle_results.txt
python track_alt.py -p -d Cehovin_hand >> results/particle_results.txt
python track_alt.py -p -d Cehovin_hand2 >> results/particle_results.txt
python track_alt.py -p -d Cehovin_torus >> results/particle_results.txt
python track_alt.py -p -d Ellis_ijcv2011_head_motion >> results/particle_results.txt
python track_alt.py -p -d Ellis_ijcv2011_track_running >> results/particle_results.txt
python track_alt.py -p -d Ellis_ijcv2011_shaking_camera >> results/particle_results.txt
python track_alt.py -p -d Godec_cliff-dive1 >> results/particle_results.txt
python track_alt.py -p -d Godec_cliff-dive2 >> results/particle_results.txt
python track_alt.py -p -d Godec_motocross1 >> results/particle_results.txt
python track_alt.py -p -d Godec_motocross2 >> results/particle_results.txt
python track_alt.py -p -d Godec_mountain-bike >> results/particle_results.txt
python track_alt.py -p -d Godec_skiing >> results/particle_results.txt
python track_alt.py -p -d Godec_volleyball >> results/particle_results.txt
python track_alt.py -p -d Kalal_car >> results/particle_results.txt
python track_alt.py -p -d Kalal_CarChase >> results/particle_results.txt
python track_alt.py -p -d Kalal_david >> results/particle_results.txt
python track_alt.py -p -d Kalal_jumping >> results/particle_results.txt
python track_alt.py -p -d Kalal_Motocross >> results/particle_results.txt
python track_alt.py -p -d Kalal_Panda >> results/particle_results.txt
python track_alt.py -p -d Kalal_pedestrian3 >> results/particle_results.txt
python track_alt.py -p -d Kalal_pedestrian4 >> results/particle_results.txt
python track_alt.py -p -d Kalal_pedestrian5 >> results/particle_results.txt
python track_alt.py -p -d Kwon_diving >> results/particle_results.txt
python track_alt.py -p -d Kwon_gym  >> results/particle_results.txt
python track_alt.py -p -d Kwon_jump >> results/particle_results.txt
python track_alt.py -p -d Kwon_trans >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_animal >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_basketball >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_football >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_shaking >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_singer1 >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_singer2 >> results/particle_results.txt
python track_alt.py -p -d Kwon_VTD_skating2 >> results/particle_results.txt
python track_alt.py -p -d Other_Asada >> results/particle_results.txt
python track_alt.py -p -d Other_drunk2 >> results/particle_results.txt
python track_alt.py -p -d Other_dudek-face >> results/particle_results.txt
python track_alt.py -p -d Other_faceocc1 >> results/particle_results.txt
python track_alt.py -p -d Other_figure_skating >> results/particle_results.txt
python track_alt.py -p -d Other_woman >> results/particle_results.txt
python track_alt.py -p -d PROST_board >> results/particle_results.txt
python track_alt.py -p -d PROST_box >> results/particle_results.txt
python track_alt.py -p -d PROST_lemming >> results/particle_results.txt
python track_alt.py -p -d PROST_liquor >> results/particle_results.txt
python track_alt.py -p -d Ross_car11 >> results/particle_results.txt
python track_alt.py -p -d Ross_dog1 >> results/particle_results.txt
python track_alt.py -p -d Ross_Sylvestr >> results/particle_results.txt
python track_alt.py -p -d Ross_trellis >> results/particle_results.txt
python track_alt.py -p -d Thang_coke >> results/particle_results.txt
python track_alt.py -p -d Thang_person >> results/particle_results.txt
python track_alt.py -p -d Thang_tiger1 >> results/particle_results.txt
python track_alt.py -p -d Thang_tiger2 >> results/particle_results.txt
python track_alt.py -p -d Wang_bird_1 >> results/particle_results.txt
python track_alt.py -p -d Wang_bird_2 >> results/particle_results.txt
python track_alt.py -p -d Wang_bolt >> results/particle_results.txt
python track_alt.py -p -d Wang_girl_mov >> results/particle_results.txt