python track.py -t TLD -d Professor_car1 >> results/tld_results.txt
python track.py -t TLD -d Professor_car2 >> results/tld_results.txt
python track.py -t TLD -d Babenko_OccludedFace2 >> results/tld_results.txt
python track.py -t TLD -d Babenko_surfer >> results/tld_results.txt
python track.py -t TLD -d Cehovin_dinosaur >> results/tld_results.txt
python track.py -t TLD -d Cehovin_gymnastics >> results/tld_results.txt
python track.py -t TLD -d Cehovin_hand >> results/tld_results.txt
python track.py -t TLD -d Cehovin_hand2 >> results/tld_results.txt
python track.py -t TLD -d Cehovin_torus >> results/tld_results.txt
python track.py -t TLD -d Ellis_ijcv2011_head_motion >> results/tld_results.txt
python track.py -t TLD -d Ellis_ijcv2011_track_running >> results/tld_results.txt
python track.py -t TLD -d Ellis_ijcv2011_shaking_camera >> results/tld_results.txt
python track.py -t TLD -d Godec_cliff-dive1 >> results/tld_results.txt
python track.py -t TLD -d Godec_cliff-dive2 >> results/tld_results.txt
python track.py -t TLD -d Godec_motocross1 >> results/tld_results.txt
python track.py -t TLD -d Godec_motocross2 >> results/tld_results.txt
python track.py -t TLD -d Godec_mountain-bike >> results/tld_results.txt
python track.py -t TLD -d Godec_skiing >> results/tld_results.txt
python track.py -t TLD -d Godec_volleyball >> results/tld_results.txt
python track.py -t TLD -d Kalal_car >> results/tld_results.txt
python track.py -t TLD -d Kalal_CarChase >> results/tld_results.txt
python track.py -t TLD -d Kalal_david >> results/tld_results.txt
python track.py -t TLD -d Kalal_jumping >> results/tld_results.txt
python track.py -t TLD -d Kalal_Motocross >> results/tld_results.txt
python track.py -t TLD -d Kalal_Panda >> results/tld_results.txt
python track.py -t TLD -d Kalal_pedestrian3 >> results/tld_results.txt
python track.py -t TLD -d Kalal_pedestrian4 >> results/tld_results.txt
python track.py -t TLD -d Kalal_pedestrian5 >> results/tld_results.txt
python track.py -t TLD -d Kwon_diving >> results/tld_results.txt
python track.py -t TLD -d Kwon_gym  >> results/tld_results.txt
python track.py -t TLD -d Kwon_jump >> results/tld_results.txt
python track.py -t TLD -d Kwon_trans >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_animal >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_basketball >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_football >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_shaking >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_singer1 >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_singer2 >> results/tld_results.txt
python track.py -t TLD -d Kwon_VTD_skating2 >> results/tld_results.txt
python track.py -t TLD -d Other_Asada >> results/tld_results.txt
python track.py -t TLD -d Other_drunk2 >> results/tld_results.txt
python track.py -t TLD -d Other_dudek-face >> results/tld_results.txt
python track.py -t TLD -d Other_faceocc1 >> results/tld_results.txt
python track.py -t TLD -d Other_figure_skating >> results/tld_results.txt
python track.py -t TLD -d Other_woman >> results/tld_results.txt
python track.py -t TLD -d PROST_board >> results/tld_results.txt
python track.py -t TLD -d PROST_box >> results/tld_results.txt
python track.py -t TLD -d PROST_lemming >> results/tld_results.txt
python track.py -t TLD -d PROST_liquor >> results/tld_results.txt
python track.py -t TLD -d Ross_car11 >> results/tld_results.txt
python track.py -t TLD -d Ross_dog1 >> results/tld_results.txt
python track.py -t TLD -d Ross_Sylvestr >> results/tld_results.txt
python track.py -t TLD -d Ross_trellis >> results/tld_results.txt
python track.py -t TLD -d Thang_coke >> results/tld_results.txt
python track.py -t TLD -d Thang_person >> results/tld_results.txt
python track.py -t TLD -d Thang_tiger1 >> results/tld_results.txt
python track.py -t TLD -d Thang_tiger2 >> results/tld_results.txt
python track.py -t TLD -d Wang_bird_1 >> results/tld_results.txt
python track.py -t TLD -d Wang_bird_2 >> results/tld_results.txt
python track.py -t TLD -d Wang_bolt >> results/tld_results.txt
python track.py -t TLD -d Wang_girl_mov >> results/tld_results.txt