python track_alt.py -d Professor_car1 >> results/template_results.txt
python track_alt.py -d Professor_car2 >> results/template_results.txt
python track_alt.py -d Babenko_OccludedFace2 >> results/template_results.txt
python track_alt.py -d Babenko_surfer >> results/template_results.txt
python track_alt.py -d Cehovin_dinosaur >> results/template_results.txt
python track_alt.py -d Cehovin_gymnastics >> results/template_results.txt
python track_alt.py -d Cehovin_hand >> results/template_results.txt
python track_alt.py -d Cehovin_hand2 >> results/template_results.txt
python track_alt.py -d Cehovin_torus >> results/template_results.txt
python track_alt.py -d Ellis_ijcv2011_head_motion >> results/template_results.txt
python track_alt.py -d Ellis_ijcv2011_track_running >> results/template_results.txt
python track_alt.py -d Ellis_ijcv2011_shaking_camera >> results/template_results.txt
python track_alt.py -d Godec_cliff-dive1 >> results/template_results.txt
python track_alt.py -d Godec_cliff-dive2 >> results/template_results.txt
python track_alt.py -d Godec_motocross1 >> results/template_results.txt
python track_alt.py -d Godec_motocross2 >> results/template_results.txt
python track_alt.py -d Godec_mountain-bike >> results/template_results.txt
python track_alt.py -d Godec_skiing >> results/template_results.txt
python track_alt.py -d Godec_volleyball >> results/template_results.txt
python track_alt.py -d Kalal_car >> results/template_results.txt
python track_alt.py -d Kalal_CarChase >> results/template_results.txt
python track_alt.py -d Kalal_david >> results/template_results.txt
python track_alt.py -d Kalal_jumping >> results/template_results.txt
python track_alt.py -d Kalal_Motocross >> results/template_results.txt
python track_alt.py -d Kalal_Panda >> results/template_results.txt
python track_alt.py -d Kalal_pedestrian3 >> results/template_results.txt
python track_alt.py -d Kalal_pedestrian4 >> results/template_results.txt
python track_alt.py -d Kalal_pedestrian5 >> results/template_results.txt
python track_alt.py -d Kwon_diving >> results/template_results.txt
python track_alt.py -d Kwon_gym  >> results/template_results.txt
python track_alt.py -d Kwon_jump >> results/template_results.txt
python track_alt.py -d Kwon_trans >> results/template_results.txt
python track_alt.py -d Kwon_VTD_animal >> results/template_results.txt
python track_alt.py -d Kwon_VTD_basketball >> results/template_results.txt
python track_alt.py -d Kwon_VTD_football >> results/template_results.txt
python track_alt.py -d Kwon_VTD_shaking >> results/template_results.txt
python track_alt.py -d Kwon_VTD_singer1 >> results/template_results.txt
python track_alt.py -d Kwon_VTD_singer2 >> results/template_results.txt
python track_alt.py -d Kwon_VTD_skating2 >> results/template_results.txt
python track_alt.py -d Other_Asada >> results/template_results.txt
python track_alt.py -d Other_drunk2 >> results/template_results.txt
python track_alt.py -d Other_dudek-face >> results/template_results.txt
python track_alt.py -d Other_faceocc1 >> results/template_results.txt
python track_alt.py -d Other_figure_skating >> results/template_results.txt
python track_alt.py -d Other_woman >> results/template_results.txt
python track_alt.py -d PROST_board >> results/template_results.txt
python track_alt.py -d PROST_box >> results/template_results.txt
python track_alt.py -d PROST_lemming >> results/template_results.txt
python track_alt.py -d PROST_liquor >> results/template_results.txt
python track_alt.py -d Ross_car11 >> results/template_results.txt
python track_alt.py -d Ross_dog1 >> results/template_results.txt
python track_alt.py -d Ross_Sylvestr >> results/template_results.txt
python track_alt.py -d Ross_trellis >> results/template_results.txt
python track_alt.py -d Thang_coke >> results/template_results.txt
python track_alt.py -d Thang_person >> results/template_results.txt
python track_alt.py -d Thang_tiger1 >> results/template_results.txt
python track_alt.py -d Thang_tiger2 >> results/template_results.txt
python track_alt.py -d Wang_bird_1 >> results/template_results.txt
python track_alt.py -d Wang_bird_2 >> results/template_results.txt
python track_alt.py -d Wang_bolt >> results/template_results.txt
python track_alt.py -d Wang_girl_mov >> results/template_results.txt